openapi: '3.0.3'
info:
  title: API Service
  description: 'Inferred from GitHub repo: iMRHACKER/CODETEST.git'
  version: '1.0.0'
  x-owner: 'iMRHACKER'
  x-generated-by: 'CodeGPO Nexus'

paths:
  /api_service:
    get:
      summary: List API Service resources
      operationId: listApiService
      tags:
        - ApiService
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiService'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api_service/{id}:
    get:
      summary: Get API Service by ID
      operationId: getApiService
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: API Service object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiService'
        '404':
          description: Not found

components:
  schemas:
  ApiService:
    type: object
    properties:
      id:
        type: string
        format: uuid
      created_at:
        type: string
        format: date-time