-- ─────────────────────────────────────────────
-- Table: saas_template_master
-- Generated by CodeGPO Nexus — 2026-02-28
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS saas_template_master (
  updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
  id                   UUID DEFAULT gen_random_uuid() NOT NULL,
  PRIMARY KEY (id)
);
