-- ─────────────────────────────────────────────
-- Table: shared
-- Generated by CodeGPO Nexus — 2026-04-07
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shared (
  updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
  id                   UUID DEFAULT gen_random_uuid() NOT NULL,
  PRIMARY KEY (id)
);
